config/routes.rb
Rails.application.routes.draw do
  resources :berita
  root 'utama#index'
end

app/models/beritum.rb
class Beritum < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/berita_controller.rb
class BeritaController < ApplicationController
  before_action :set_beritum, only: [:show, :edit, :update, :destroy]

  # GET /berita
  # GET /berita.json
  def index
    @berita = Beritum.all
  end

  # GET /berita/1
  # GET /berita/1.json
  def show
  end

  # GET /berita/new
  def new
    @beritum = Beritum.new
  end

  # GET /berita/1/edit
  def edit
  end

  # POST /berita
  # POST /berita.json
  def create
    @beritum = Beritum.new(beritum_params)

    respond_to do |format|
      if @beritum.save
        format.html { redirect_to @beritum, notice: 'Beritum was successfully created.' }
        format.json { render :show, status: :created, location: @beritum }
      else
        format.html { render :new }
        format.json { render json: @beritum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /berita/1
  # PATCH/PUT /berita/1.json
  def update
    respond_to do |format|
      if @beritum.update(beritum_params)
        format.html { redirect_to @beritum, notice: 'Beritum was successfully updated.' }
        format.json { render :show, status: :ok, location: @beritum }
      else
        format.html { render :edit }
        format.json { render json: @beritum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /berita/1
  # DELETE /berita/1.json
  def destroy
    @beritum.destroy
    respond_to do |format|
      format.html { redirect_to berita_url, notice: 'Beritum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beritum
      @beritum = Beritum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beritum_params
      params.require(:beritum).permit(:judul, :isi)
    end
end

app/controllers/utama_controller.rb
class UtamaController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/berita_helper.rb
module BeritaHelper
end

app/helpers/utama_helper.rb
module UtamaHelper
end

app/views/berita/_form.html.erb
<%= form_for(@beritum) do |f| %>
  <% if @beritum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beritum.errors.count, "error") %> prohibited this beritum from being saved:</h2>

      <ul>
      <% @beritum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :judul %><br>
    <%= f.text_field :judul %>
  </div>
  <div class="field">
    <%= f.label :isi %><br>
    <%= f.text_area :isi %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/berita/edit.html.erb
<h1>Editing Beritum</h1>

<%= render 'form' %>

<%= link_to 'Show', @beritum %> |
<%= link_to 'Back', berita_path %>

app/views/berita/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Berita</h1>

<table>
  <thead>
    <tr>
      <th>Judul</th>
      <th>Isi</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @berita.each do |beritum| %>
      <tr>
        <td><%= beritum.judul %></td>
        <td><%= beritum.isi %></td>
        <td><%= link_to 'Show', beritum %></td>
        <td><%= link_to 'Edit', edit_beritum_path(beritum) %></td>
        <td><%= link_to 'Destroy', beritum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beritum', new_beritum_path %>

app/views/berita/new.html.erb
<h1>New Beritum</h1>

<%= render 'form' %>

<%= link_to 'Back', berita_path %>

app/views/berita/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Judul:</strong>
  <%= @beritum.judul %>
</p>

<p>
  <strong>Isi:</strong>
  <%= @beritum.isi %>
</p>

<%= link_to 'Edit', edit_beritum_path(@beritum) %> |
<%= link_to 'Back', berita_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxJQuery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<div class="row">
		<%= yield %>
	</div>
</div>

</body>
</html>

app/views/utama/index.html.erb
<!-- <div class="card blue-grey darken-1">
<div class="card-content white-text">
  <span class="card-title">Card Title</span>
  <p>I am a very simple card. I am good at containing small bits of information.
  I am convenient because I require little markup to use effectively.</p>
</div>
<div class="card-action">
  <a href="#">This is a link</a>
  <a href="#">This is a link</a>
</div>
</div> -->
<div class="col l5 s12">
	<div class="fixed col l3">
		<div class="card">
			<div class="card-content">
				<span class="card-title">Tambah Berita</span>
				<div class="input-field col s12">
					Judul:
					<input id="judul" type="text" class="validate">
				</div>
				<div class="input-field col s12">
					Isi:
					<input id="isi" type="text" class="validate">
				</div>
				<div class="action">
					<button id="add-berita" class="waves-effect waves-light btn red lighten-2" >Tambah!</button>
					<button id="simpan" class="waves-effect waves-light btn red lighten-2 edit" >Simpan!</button>
				</div>
			</div>
		</div>
		<div class="card grey lighten-3">
			<div class="card-image">
				<img src="images/MyLogo.png" height="240px">
            </div>
			<div class="card-content center">
				Copyright&copy;2015 Keramas Wiguna<br>
				Make With <span class="pink-text">Love</span> in Penarungan, Bali
			</div>
		</div>
	</div>
</div>
<div class="col l8 right">
	<div class="col l12 s12">
		<div id="cont-pesan" class="card center">
			<span id="pesan" class="card-title red-text"></span>
		</div>
	<div class="col l12 s12">
		<div class="card">
			<div class="card-content">
				<h1>Berita</h1>
				<ul id="berita" class="collection with-header">
					<li><h4 id="kosong"></h4></li>
				</ul>
			</div>
		</div>
	</div>
</div>